backend/controllers/PermissionController.php
<?php

namespace backend\controllers;


use backend\models\PermissionForm;
use Yii;
use yii\data\ArrayDataProvider;
use yii\filters\VerbFilter;
use yii\rbac\Permission;
use yii\web\NotFoundHttpException;

class PermissionController extends BaseController
{
    /**
     * @return array
     */
    public function behaviors()
    {
        return array_merge(parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['post'],
                        'save' => ['post'],
                    ],
                ],
            ]);
    }

    /**
     * @param null $name
     * @return string|\yii\web\Response
     */
    public function actionIndex($name = null)
    {
        $authManager = Yii::$app->getAuthManager();
        $permissions = $authManager->getPermissions();
        $roles = $authManager->getRoles();
        if ($name !== null) {
            foreach ($roles as $role) {
                if ($role->name === $name) {
                    $roles = [$role];
                    break;
                }
            }
        }

        $roleChildrenList = [];
        foreach ($roles as $role) {
            $roleChildrenList[$role->name] = $authManager->getChildren($role->name);
        }

        $permissionChildren = [];
        foreach ($permissions as &$permission) {
            $permission = (array)$permission;
            $permission['roles'] = [];

            if (preg_match('#^[A-z0-9\-_]+:$#', $permission['name'])) {
                $permission['is_valid'] = false;
            } else {
                $permission['is_valid'] = true;
            }

            foreach ($roleChildrenList as $roleName => $children) {
                foreach ($children as $child) {
                    if ($child->name === $permission['name']) {
                        $permission['roles'][] = $roleName;
                    }
                }
            }

            if ($pos = strrpos($permission['name'], '/')) {
                $parent = substr($permission['name'], 0, $pos);
                $permission['parent'] = $parent;
                $permissionChildren[$parent][] = $permission;
            } else {
                $permission['parent'] = 0;
                $permissionChildren[0][] = $permission;
            }
        }

        foreach ($permissionChildren as &$children) {
            foreach ($children as &$child) {
                if (isset($permissionChildren[$child['name']])) {
                    $child['is_parent'] = true;
                } else {
                    $child['is_parent'] = false;
                }
            }
        }

        return $this->render('index', array(
            'roles' => $roles,
            'dataProvider' => new ArrayDataProvider(['models' => $this->generateTree($permissionChildren)]),
        ));
    }

    /**
     * 保存权限
     *
     * @return \yii\web\Response
     */
    public function actionSave()
    {
        if (isset($_POST['permission'])) {
            $newPermissionList = (array) $_POST['permission'];
            $authManager = Yii::$app->authManager;
            $roles = $authManager->getRoles();
            $permissions = $authManager->getPermissions();

            $oldPermissionList = [];
            foreach ($roles as $name => $role) {
                if (isset($newPermissionList[$name])) {
                    foreach ($authManager->getChildren($role->name) as $permission) {
                        $oldPermissionList[$role->name][] = $permission->name;
                    }
                }
            }
            $addPermissionList = [];
            $delPermissionList = [];

            foreach ($newPermissionList as $roleName => $permissionList) {
                foreach ($permissionList as $i => $name) {
                    if (preg_match('#^[A-z0-9\-\_]+:$#', $name)) {
                        unset($permissionList[$i]);
                    }
                }
                $permissionList = is_array($permissionList) ? $permissionList : [];
                $_oldPermissionList = isset($oldPermissionList[$roleName]) ? $oldPermissionList[$roleName] : [];
                $addPermissionList[$roleName] = array_diff($permissionList , $_oldPermissionList);
                $delPermissionList[$roleName] = array_diff($_oldPermissionList , $permissionList);
            }

            foreach ($addPermissionList as $roleName => $permissionNames) {
                foreach ($permissionNames as $permissionName) {
                    if (isset($roles[$roleName]) && isset($permissions[$permissionName])) {
                        $authManager->addChild($roles[$roleName], $permissions[$permissionName]);
                    }
                }
            }

            foreach ($delPermissionList as $roleName => $permissionNames) {
                foreach ($permissionNames as $permissionName) {
                    if (isset($roles[$roleName]) && isset($permissions[$permissionName])) {
                        $authManager->removeChild($roles[$roleName], $permissions[$permissionName]);
                    }
                }
            }

            Yii::$app->session->setFlash('success', '权限保存成功。');
        }
        return $this->redirect(['index']);
    }

    /**
     * 生成权系树
     *
     * @param $children
     * @param int $parent
     * @param null $maxDepth
     * @return array
     */
    protected function generateTree($children, $parent = 0, $maxDepth = null)
    {
        if ($maxDepth === null) {
            $maxDepth = count($children);
        }

        $processParents = array();
        $tree = array();

        $processParents[] = $parent;
        while (count($processParents)) {
            $parent = array_pop($processParents);
            $depth = count($processParents);

            if ($maxDepth > $depth && !empty($children[$parent])) {
                $hasChildren = false;
                $child = current($children[$parent]);

                do {
                    if (empty($child)) {
                        break;
                    }

                    $child['depth'] = $depth;
                    $tree[] = $child;

                    if (!empty($children[$child['name']])) {
                        $hasChildren = true;
                        $processParents[] = $parent;
                        $processParents[] = $child['name'];
                        reset($children[$child['name']]);
                        next($children[$parent]);
                        break;
                    }
                } while ($child = next($children[$parent]));

                if (!$hasChildren) {
                    reset($children[$parent]);
                }
            }
        }

        return $tree;
    }

    /**
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new PermissionForm();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', '权限创建成功。');
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * @param $name
     * @return string|\yii\web\Response
     */
    public function actionUpdate($name)
    {
        $model = new PermissionForm($this->loadModel($name));
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', '权限更新成功。');
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * @param $name
     * @return \yii\web\Response
     */
    public function actionDelete($name)
    {
        $permission = $this->loadModel($name);
        Yii::$app->authManager->remove($permission)
        &&
        Yii::$app->session->setFlash('success', '权限删除成功。');
        return $this->redirect(['index']);
    }

    /**
     * @param $name
     * @return Permission
     * @throws \yii\web\NotFoundHttpException
     */
    public function loadModel($name)
    {
        $authManager = Yii::$app->getAuthManager();
        if (!$permission = $authManager->getPermission($name)) {
            throw new NotFoundHttpException('The requested page does not exist.');
        } else {
            return $permission;
        }
    }
} 

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use backend\models\PasswordForm;
use common\models\batch\UserBatch;
use common\models\search\UserSearch;
use common\models\User;
use Yii;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends BaseController
{
    public function behaviors()
    {
        return array_merge(parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['post'],
                    ],
                ],
            ]);
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $batchModel = new UserBatch();
        if (isset($_POST['id'])) {
            $result = $batchModel->process($_POST['id'], $_POST);
            if (is_string($result)) {
                Yii::$app->getSession()->setFlash('success', $result);
                return $this->redirect(Yii::$app->getRequest()->getAbsoluteUrl());
            }
        }

        $searchModel = new UserSearch();

        return $this->render('index', [
            'dataProvider' => $searchModel->search($_GET),
            'searchModel' => $searchModel,
            'batchModel' => $batchModel,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $this->menuRoute = false;
        $model = new User(['scenario' => 'create']);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', '用户创建成功。');
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        if ($id === Yii::$app->getUser()->getId()) {
            return $this->redirect(['profile']);
        }

        $model = $this->findModel($id);
        $passwordForm = new PasswordForm();
        $post = Yii::$app->request->post();

        if ($model->load($post) && $passwordForm->load($post) && $passwordForm->validate()) {
            if ($passwordForm->password) {
                $model->setPassword($passwordForm->password);
                $model->generateAuthKey();
            }
            if ($model->save()) {
                Yii::$app->session->setFlash('success', '用户更新成功。');
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
            'passwordForm' => $passwordForm,
        ]);
    }

    /**
     * @return string|\yii\web\Response
     */
    public function actionProfile()
    {
        $model = $this->findModel(Yii::$app->user->getId());
        $model->setScenario('profile');
        $passwordForm = new PasswordForm();
        $post = Yii::$app->request->post();

        if ($model->load($post) && $passwordForm->load($post) && $passwordForm->validate()) {
            if ($passwordForm->password) {
                $model->setPassword($passwordForm->password);
                $model->generateAuthKey();
            }

            if ($model->save()) {
                Yii::$app->session->setFlash('success', '个人资料更新成功。');
                return $this->redirect(['profile']);
            }
        }

        return $this->render('profile', [
            'model' => $model,
            'passwordForm' => $passwordForm,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete()
        &&
        Yii::$app->session->setFlash('success', '用户删除成功。');
        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/permission/_form.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\PermissionForm */
/* @var $form yii\bootstrap\ActiveForm */
?>

<div class="permission-form">

    <?php $form = ActiveForm::begin(['layout' => 'horizontal']); ?>

    <?= $form->field($model, 'name')->textInput()->hint('必须唯一') ?>

    <?= $form->field($model, 'description')->textInput() ?>

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-6">
            <?= Html::submitButton($model->isNew ? '创建' : '更新', ['class' => $model->isNew ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/permission/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\PermissionForm */

$this->title = '创建权限';
$this->params['breadcrumbs'][] = ['label' => '用户', 'url' => ['/user/index']];
$this->params['breadcrumbs'][] = ['label' => '权限', 'url' => ['/permission/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="permission-create">
    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

backend/views/permission/index.php
<?php

use yii\bootstrap\ActiveForm;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Inflector;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $roles yii\rbac\Role[] */

$this->title = '权限';
$this->params['breadcrumbs'][] = ['label' => '用户', 'url' => ['/user/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="permission-index">
    <h1>
        <?= Html::encode($this->title) ?>
        <?= Html::a('创建权限', ['create'], ['class' => 'btn btn-sm btn-success']) ?>
    </h1>

    <?php
    $form = ActiveForm::begin(['action' => ['save'], 'id' => 'savePermissionsForm']);
    $columns = [
        [
            'attribute' => 'name',
            'label' => '名称',
            'content' => function($model) {
                    return '<div class="depth-' . $model['depth'] . '">' . '<code>' . $model['name'] . ' </code>'
                    . Html::a('<small class="glyphicon glyphicon-pencil"></small>', ['update', 'name' => $model['name']], ['title' => '更新权限“' . $model['description'] . '”']) .
                    (!$model['is_parent'] ?
                    Html::a('<small class="glyphicon glyphicon-trash"></small>', ['delete', 'name' => $model['name']], [
                        'data-confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
                        'data-method' => 'post',
                        'data-pjax' => '0',
                    ]) : '')
                    . '<div class="description">'
                    . $model['description']
                    . '</div>'
                    . '</div>';
                }
        ],
    ];
    foreach ($roles as $role) {
        echo Html::hiddenInput('permission['. $role->name .']');
        $columns[] = [
            'label' => $role->description,
            'content' => function($model) use ($role) {
                if ($model['is_valid']) {
                    $check = in_array($role->name, $model['roles']);
                    return Html::checkbox('permission['. $role->name .'][]', $check, ['value' => $model['name'], 'data-role' => $role->name]);
                } else {
                    return '';
                }
            }
        ];
    }
    ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => $columns,
        'rowOptions' => function($model) {
            return ['data-parent' => $model['parent']];
        }
    ]); ?>
    <?= Html::submitButton('保存', ['class' =>'btn btn-primary']) ?>
    <?php ActiveForm::end() ?>
</div>
<?php
$js = <<<EOT
(function($) {
var form = $('#savePermissionsForm');
form.find('input:checkbox').click(function() {
    var value = $(this).val(),
        role = $(this).data('role'),
        parent;
    if (this.checked) {
        form.find('tr').each(function() {
            if ($(this).data('parent') === value) {
                $(this).find('input[data-role="' + role + '"]').prop('checked', true);
            }
        });
    } else {
        parent = $(this).parents('tr');
        $('input[value="' + parent.data('parent') + '"]').prop('checked', false);
    }
});
})(jQuery);
EOT;
$this->registerJs($js);

backend/views/permission/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\PermissionForm */

$this->title = '更新权限';
$this->params['breadcrumbs'][] = ['label' => '用户', 'url' => ['/user/index']];
$this->params['breadcrumbs'][] = ['label' => '权限', 'url' => ['/permission/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="permission-update">
    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>