backend/models/RoleForm.php
<?php

namespace backend\models;


use yii\base\Model;
use Yii;
use yii\rbac\Role;

/**
 * Class RoleForm
 *
 * @property bool $isNew
 * @package backend\models
 */
class RoleForm extends Model
{
    public $name;
    public $description;

    private $_role;

    public function __construct(Role $role = null, $config = [])
    {
        parent::__construct($config);
        if ($role !== null) {
            $this->_role = $role;
            $this->name = $role->name;
            $this->description = $role->description;
        }
    }

    public function rules()
    {
        return [
            [['name', 'description'], 'required'],
            ['name', 'match', 'pattern' => '/[a-z0-9]+/'],
            ['name', 'nameUnique'],
        ];
    }

    public function nameUnique()
    {
        if ($this->getIsNew() || $this->_role->name !== $this->name) {
            $role = Yii::$app->getAuthManager()->getRole($this->name);
            if ($role) {
                $this->addError('name', '名称已经被使用。');
            }
        }
    }

    public function attributeLabels()
    {
        return [
            'name' => '名称',
            'description' => '描述'
        ];
    }

    /**
     * @return bool
     */
    public function getIsNew()
    {
        return !isset($this->_role);
    }

    public function save()
    {
        if (!$this->validate()) {
            return false;
        }

        $authManager = Yii::$app->getAuthManager();
        if (!isset($this->_role)) {
            $role = $authManager->createRole($this->name);
            $role->description = $this->description;
            return $authManager->add($role);
        } else {
            $name = $this->_role->name;
            $this->_role->name = $this->name;
            $this->_role->description = $this->description;
            return $authManager->update($name, $this->_role);
        }
    }
} 

backend/controllers/RoleController.php
<?php
namespace backend\controllers;

use backend\models\RoleForm;
use yii\data\ArrayDataProvider;
use Yii;
use yii\filters\VerbFilter;
use yii\rbac\Role;
use yii\web\NotFoundHttpException;

class RoleController extends BaseController
{
    /**
     * @return array
     */
    public function behaviors()
    {
        return array_merge(parent::behaviors(),
        [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ]);
    }

    /**
     * @return string|\yii\web\Response
     */
    public function actionIndex()
    {
        $roles = Yii::$app->authManager->getRoles();

        return $this->render('index', [
            'dataProvider' => new ArrayDataProvider(['models' => $roles])
        ]);
    }

    /**
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new RoleForm();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', '角色创建成功。');
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * @param $name
     * @return string|\yii\web\Response
     */
    public function actionUpdate($name)
    {
        $model = new RoleForm($this->loadModel($name));
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', '角色更新成功。');
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * @param $name
     * @return \yii\web\Response
     */
    public function actionDelete($name)
    {
        $role = $this->loadModel($name);
        Yii::$app->authManager->remove($role)
        &&
        Yii::$app->session->setFlash('success', '角色删除成功。');
        return $this->redirect(['index']);
    }

    /**
     * @param $name
     * @return Role
     * @throws \yii\web\NotFoundHttpException
     */
    public function loadModel($name)
    {
        if (!$role = Yii::$app->authManager->getRole($name)) {
            throw new NotFoundHttpException('The requested page does not exist.');
        } else {
            return $role;
        }
    }
} 

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use backend\models\PasswordForm;
use common\models\batch\UserBatch;
use common\models\search\UserSearch;
use common\models\User;
use Yii;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends BaseController
{
    public function behaviors()
    {
        return array_merge(parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['post'],
                    ],
                ],
            ]);
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $batchModel = new UserBatch();
        if (isset($_POST['id'])) {
            $result = $batchModel->process($_POST['id'], $_POST);
            if (is_string($result)) {
                Yii::$app->getSession()->setFlash('success', $result);
                return $this->redirect(Yii::$app->getRequest()->getAbsoluteUrl());
            }
        }

        $searchModel = new UserSearch();

        return $this->render('index', [
            'dataProvider' => $searchModel->search($_GET),
            'searchModel' => $searchModel,
            'batchModel' => $batchModel,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $this->menuRoute = false;
        $model = new User(['scenario' => 'create']);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', '用户创建成功。');
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        if ($id === Yii::$app->getUser()->getId()) {
            return $this->redirect(['profile']);
        }

        $model = $this->findModel($id);
        $passwordForm = new PasswordForm();
        $post = Yii::$app->request->post();

        if ($model->load($post) && $passwordForm->load($post) && $passwordForm->validate()) {
            if ($passwordForm->password) {
                $model->setPassword($passwordForm->password);
                $model->generateAuthKey();
            }
            if ($model->save()) {
                Yii::$app->session->setFlash('success', '用户更新成功。');
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }

        return $this->render('update', [
            'model' => $model,
            'passwordForm' => $passwordForm,
        ]);
    }

    /**
     * @return string|\yii\web\Response
     */
    public function actionProfile()
    {
        $model = $this->findModel(Yii::$app->user->getId());
        $model->setScenario('profile');
        $passwordForm = new PasswordForm();
        $post = Yii::$app->request->post();

        if ($model->load($post) && $passwordForm->load($post) && $passwordForm->validate()) {
            if ($passwordForm->password) {
                $model->setPassword($passwordForm->password);
                $model->generateAuthKey();
            }

            if ($model->save()) {
                Yii::$app->session->setFlash('success', '个人资料更新成功。');
                return $this->redirect(['profile']);
            }
        }

        return $this->render('profile', [
            'model' => $model,
            'passwordForm' => $passwordForm,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete()
        &&
        Yii::$app->session->setFlash('success', '用户删除成功。');
        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/role/_form.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\RoleForm */
/* @var $form yii\bootstrap\ActiveForm */
?>

<div class="role-form">

    <?php $form = ActiveForm::begin(['layout' => 'horizontal']); ?>

    <?= $form->field($model, 'name')->textInput()->hint('只能包含小写英文字母，且唯一') ?>

    <?= $form->field($model, 'description')->textInput() ?>

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-6">
            <?= Html::submitButton($model->isNew ? '创建' : '更新', ['class' => $model->isNew ? 'btn btn-success' : 'btn btn-primary']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/role/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\RoleForm */

$this->title = '创建角色';
$this->params['breadcrumbs'][] = ['label' => '用户', 'url' => ['/user/index']];
$this->params['breadcrumbs'][] = ['label' => '角色', 'url' => ['/role/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="role-create">
    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

backend/views/role/index.php
<?php

use yii\grid\GridView;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = '角色';
$this->params['breadcrumbs'][] = ['label' => '用户', 'url' => ['/user/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="role-index">
    <h1>
        <?= Html::encode($this->title) ?>
        <?= Html::a('创建角色', ['create'], ['class' => 'btn btn-sm btn-success']) ?>
    </h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            [
                'attribute' => 'name',
                'label' => '名称',
                'content' => function($model) {
                    return Html::a($model->name, ['/role/update', 'name' => $model->name], ['title' => '更新角色“' . $model->name . '”']);
                }
            ],
            ['attribute' => 'description', 'label' => '描述'],
            [
                'label' => '',
                'content' => function($model) {
                    return Html::a('更新权限', ['/permission', 'name' => $model->name]);
                }
            ],
            [
                'label' => '',
                'content' => function($model) {
                    return Html::a('删除', ['delete', 'name' => $model->name], [
                        'data-confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
                        'data-method' => 'post',
                        'data-pjax' => '0',
                    ]);
                }
            ],
        ],
    ]); ?>
</div>

backend/views/role/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\RoleForm */

$this->title = '更新角色';
$this->params['breadcrumbs'][] = ['label' => '用户', 'url' => ['/user/index']];
$this->params['breadcrumbs'][] = ['label' => '角色', 'url' => ['/role/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="role-update">
    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>