backend/controllers/FileController.php
<?php

namespace backend\controllers;


use backend\models\FileSettingForm;
use common\models\batch\FileBatch;
use common\models\File;
use common\models\search\FileSearch;
use Imagine\Image\Box;
use Imagine\Image\ImageInterface;
use Imagine\Image\Point;
use yii\base\InvalidParamException;
use Yii;
use yii\filters\VerbFilter;
use yii\imagine\Image;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class FileController extends BaseController
{
    public function behaviors()
    {
        return array_merge(parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['post'],
                    ],
                ],
            ]);
    }

    public function actionIndex()
    {
        $batchModel = new FileBatch();
        if (isset($_POST['id'])) {
            $result = $batchModel->process($_POST['id'], $_POST);
            if (is_string($result)) {
                Yii::$app->getSession()->setFlash('success', $result);
                return $this->redirect(Yii::$app->getRequest()->getAbsoluteUrl());
            }
        }

        $searchModel = new FileSearch();

        return $this->render('index', [
            'dataProvider' => $searchModel->search($_GET),
            'searchModel' => $searchModel,
            'batchModel' => $batchModel,
        ]);
    }

    public function actionUpload($model = null, $field = null)
    {
        $this->menuRoute = false;

        if ($model === null || $field === null) {
            $modelClass = File::className();
            $field = 'file';
        } else {
            $modelClass = $model;
        }

        /** @var \yii\db\ActiveRecord $model */
        $model = new $modelClass(['scenario' => 'upload']);

        if ($model->load(Yii::$app->getRequest()->post()) && ($file = $model->upload($field))) {
            if (Yii::$app->getRequest()->isAjax) {
                return new Response([
                    'format' => Response::FORMAT_JSON,
                    'data' => [
                        'success' => true,
                        'attachment' => $file->toAttachment(),
                    ],
                ]);
            } else {
                Yii::$app->getSession()->setFlash('success', '文件上传成功。');
                return $this->redirect(['view', 'id' => $file->id]);
            }
        }

        if (Yii::$app->getRequest()->isAjax) {
            if ($model->hasErrors($field)) {
                $data = [
                    'success' => false,
                    'errors' => $model->getErrors($field),
                ];
            } else {
                $data = [];
            }
            return new Response([
                'format' => Response::FORMAT_JSON,
                'data' => $data,
            ]);
        } else {
            return $this->render('upload', [
                'model' => $model,
            ]);
        }
    }

    /**
     * 更新文件
     *
     * @param $id
     * @return string|Response
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', '文件更新成功。');
            return $this->redirect(['update', 'id' => $model->id]);
        }
        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * 删除文件
     *
     * @param $id
     * @return Response
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        if ($model->bundle === File::className()) {
            $model->delete()
            &&
            Yii::$app->session->setFlash('success', '文件删除成功。');
        }
        return $this->redirect(['index']);
    }

    /**
     * 删除文件
     *
     * @param $id
     * @return string
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionSettings()
    {
        $this->menuRoute = false;

        $model = new FileSettingForm();
        if ($model->load(Yii::$app->getRequest()->post()) && $model->save()) {
            Yii::$app->getSession()->setFlash('success', '媒体选项保存成功');
            return $this->redirect(['settings']);
        }

        return $this->render('settings', [
            'model' => $model,
        ]);
    }

    /**
     * 图片编辑预览
     *
     * @param $id
     * @throws \yii\base\InvalidParamException
     */
    public function actionImgeditPreview($id)
    {
        $model = $this->findModel($id);
        if (!$model->isImage()) {
            throw new InvalidParamException('文件不是图片类型');
        }

        $image = Image::getImagine()->open($model->getPath());
        $changes = !empty($_REQUEST['history']) ? json_decode($_REQUEST['history']) : null;
        if ($changes) {
            $this->imageEditApplyChanges($image, $changes);
        }
        $size = $image->getSize();
        $ratio = $this->imageEditPreviewRatio($size->getWidth(), $size->getHeight());
        $image->resize($size->scale($ratio));
        $image->show($model->getExtension());
    }

    /**
     * 获取图片编辑器
     *
     * @param $id
     * @return string|Response
     * @throws \yii\base\InvalidParamException
     */
    public function actionImageEditor($id)
    {
        $model = $this->findModel($id);
        if (!$model->isImage()) {
            throw new InvalidParamException('文件不是图片类型');
        }

        if (isset($_POST['do'])) {
            switch ($_POST['do']) {
                case 'save':
                case 'scale':
                    $image = Image::getImagine()->open($model->getPath());

                    if ($_POST['do'] === 'save') {
                        $changes = !empty($_REQUEST['history']) ? json_decode($_REQUEST['history']) : null;
                        $target = !empty($_REQUEST['target']) ? preg_replace('/[^a-z0-9_-]+/i', '', $_REQUEST['target']) : '';
                        if ($changes) {
                            $this->imageEditApplyChanges($image, $changes);
                        }
                    } else {
                        $fWidth = !empty($_REQUEST['fwidth']) ? intval($_REQUEST['fwidth']) : 0;
                        $fHeight = !empty($_REQUEST['fheight']) ? intval($_REQUEST['fheight']) : 0;

                        $box = $image->getSize();
                        $sX = $box->getWidth();
                        $sY = $box->getHeight();

                        // check if it has roughly the same w / h ratio
                        $diff = round($sX / $sY, 2) - round($fWidth / $fHeight, 2);
                        if (-0.1 < $diff && $diff < 0.1) {
                            // scale the full size image
                            $image->resize(new Box($fWidth, $fHeight));
                            $target = 'scale';
                        } else {
                            $result = array('error' => '图片拉伸失败');
                            break;
                        }
                    }

                    $result = $this->saveImage($model, $image, $target);
                    if ($_POST['do'] == 'save') {
                        return new Response([
                            'format' => Response::FORMAT_JSON,
                            'data' => $result,
                        ]);
                    }
                    break;
                case 'restore':
                    $result = $this->restoreImage($model);
                    break;
            }
        }

        $dimensions = $model->getDimensions();
        if ($dimensions === false) {
            throw new InvalidParamException('图片长宽不正确，请重新上传。');
        } else {
            $width = $dimensions['width'];
            $height = $dimensions['height'];
        }

        $sizer = $this->imageEditPreviewRatio($width, $height);

        $sizes = $model->getImageSizes();

        if (isset($sizes[File::IMAGE_THUMBNAIL])) {
            $thumbW = $sizes[File::IMAGE_THUMBNAIL]['width'];
            $thumbH = $sizes[File::IMAGE_THUMBNAIL]['height'];
        } elseif (isset($sizes[File::IMAGE_ORIGIN])) {
            $thumbW = $sizes[File::IMAGE_ORIGIN]['width'];
            $thumbH = $sizes[File::IMAGE_ORIGIN]['height'];
        } else {
            $thumbW = 160;
            $thumbH = 120;
        }

        list($thumbW, $thumbH) = $model->constrainDimensions($thumbW, $thumbH, 160, 120);

        $meta = $model->getMeta();

        $backupSizes = isset($meta['_backup_sizes']) ? $meta['_backup_sizes'] : false;
        $canRestore = false;

        if (!empty($backupSizes) && isset($backupSizes[File::IMAGE_ORIGIN . '-orig'], $model->uri)) {
            $canRestore = $backupSizes[File::IMAGE_ORIGIN . '-orig']['uri'] != $model->uri;
        }

        return $this->renderAjax('_imageEditor', [
            'id' => $id,
            'model' => $this->findModel($id),
            'canRestore' => $canRestore,
            'thumbW' => $thumbW,
            'thumbH' => $thumbH,
            'width' => $width,
            'height' => $height,
            'sizer' => $sizer,
            'result' => isset($result) ? $result : [],
        ]);
    }

    /**
     * 重新还图片
     *
     * @param \common\models\File $model
     * @return array
     */
    protected function restoreImage(File $model)
    {
        $meta = $model->getMeta();
        if (isset($meta['_backup_sizes'])) {
            $backupSizes = $meta['_backup_sizes'];
        } else {
            return [
                'error' => '没有找到图片备份信息'
            ];
        }

        $dimensions = $model->getDimensions();
        $filePath = $model->getPath();
        $parts = pathinfo($filePath);
        $suffix = time() . rand(100, 999);
        if (isset($backupSizes[File::IMAGE_ORIGIN . '-orig']) && is_array($backupSizes[File::IMAGE_ORIGIN . '-orig'])) {

backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use backend\models\LostPasswordForm;
use backend\models\ResetPasswordForm;
use backend\models\SettingForm;
use Yii;
use yii\base\InvalidParamException;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use backend\models\LoginForm;
use yii\filters\VerbFilter;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;

/**
 * Site controller
 */
class SiteController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error', 'lost-password', 'reset-password'],
                        'allow' => true,
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ]);
    }

    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            if ($action->id === 'error') {
                $this->layout = 'error';
            }
            return true;
        } else {
            return false;
        }
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        $this->layout = 'login';

        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionLostPassword()
    {
        $this->layout = 'login';

        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LostPasswordForm();
        if ($model->load(Yii::$app->request->post()) && $model->sendEmail()) {
            Yii::$app->session->setFlash('success', '密码重置邮件已发送。');
            return $this->redirect(['login']);
        } else {
            return $this->render('lostPassword', [
                'model' => $model,
            ]);
        }
    }

    public function actionResetPassword($token)
    {
        $this->layout = 'login';

        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->getSession()->setFlash('success', '新密码已保存。');
            return $this->redirect(['login']);
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * @param string $category
     * @return string|\yii\web\Response
     * @throws \yii\web\NotFoundHttpException
     * @throws \yii\web\ForbiddenHttpException
     */
    public function actionSettings($category)
    {
        $this->menuRoute = false;

        try {
            $model = new SettingForm($category);
        } catch (InvalidParamException $e) {
            throw new NotFoundHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->getSession()->setFlash('success', $model->getTitle() . '已保存。');
            return $this->redirect(['settings', 'category' => $category]);
        }

        return $this->render('settings', [
            'model' => $model,
            'category' => $category
        ]);
    }
}

backend/views/file/_imageEditor.php
<?php
use common\models\File;
use yii\helpers\Url;

/** @var integer $id */
/** @var integer $width */
/** @var integer $height */
/** @var integer $thumbW */
/** @var integer $thumbH */
/** @var bool $canRestore */
/** @var \common\models\File $model */
/** @var integer $sizer */

$note = '';
if ( isset($result) ) {
    if ( isset($result['error']) )
        $note = "<div class='alert alert-error'>{$result['error']}</div>";
    elseif ( isset($result['msg']) )
        $note = "<div class='alert alert-success'>{$result['msg']}</div>";
}
$imageSizes = File::imageSizes();
if (isset($imageSizes[File::IMAGE_THUMBNAIL])) {
    $minthumb = $imageSizes[File::IMAGE_THUMBNAIL][0] . ':' . $imageSizes[File::IMAGE_THUMBNAIL][1];
} else {
    $minthumb = '128:128';
}
?>
<div class="imgedit-wrap">
    <div id="imgedit-panel-<?= $id ?>" class="clearfix">
        <div class="imgedit-settings">
            <div class="panel panel-default imgedit-group">
                <div class="panel-heading">
                    拉伸图像 <a href="#" class="dashicons dashicons-editor-help imgedit-help-toggle"></a>
                </div>

                <div class="panel-body">
                    <div class="imgedit-help">
                        <p>您可以成比例地拉伸原始图片，在诸如裁切、旋转的编辑操作之前，最好先伸缩调整好您的图片尺寸。图片仅能被缩小，不能被放大。</p>
                    </div>
                    <p>原始尺寸<?= $width ?> &times; <?= $height ?></p>

                    <div class="imgedit-submit">
                    <span class="nowrap">
                        <input type="text" id="imgedit-scale-width-<?= $id ?>" style="width:4em;" value="<?= $width ?>"/> &times;
                        <input type="text" id="imgedit-scale-height-<?= $id ?>" style="width:4em;" value="<?= $height ?>"/>
                        <span class="imgedit-scale-warn" id="imgedit-scale-warn-<?= $id ?>">!</span>
                    </span>
                        <input type="button" class="btn btn-sm btn-primary imgedit-scale-btn" value="拉伸"/>
                    </div>
                </div>
            </div>
            <?php if ($canRestore) { ?>
                <div class="panel panel-default imgedit-group">
                    <div class="panel-heading">
                        <a href="#" class="imgedit-help-toggle">还原原始图像 <span class="dashicons dashicons-arrow-down"></span></a>
                    </div>

                    <div class="panel-body">
                        <div class="imgedit-help">
                            <p>放弃所有变更，并恢复到原始图片。 先前编辑过的图片副本不会被删除。</p>
                        </div>
                        <div class="imgedit-submit">
                            <input type="button" value="还原图像" class="btn btn-sm btn-primary imgedit-restore-btn">
                        </div>
                    </div>
                </div>
            <?php } ?>
            <div class="panel panel-default imgedit-group">
                <div class="panel-heading">
                    图像裁切 <a href="#" class="dashicons dashicons-editor-help imgedit-help-toggle"></a>
                </div>
                <div class="panel-body">

                    <div class="imgedit-help">
                        <p>要裁切此图像，点击并拖动来确认您的选择。</p>

                        <p><strong>按比例裁切</strong><br/>
                            纵横比是宽与高之间的比值。您可以通过在修改选区时按住Shift键来固定纵横比。使用输入框来指定纵横比，如1:1（方形）、4:3、16:9等。</p>

                        <p><strong>裁切选区</strong><br/>
                            您做出选择后，选区大小可以通过输入像素值值来调整。最小值为媒体设置中指定的缩略图大小。</p>
                    </div>

                    <p> 长宽比： <span class="nowrap">
                        <input type="text" id="imgedit-crop-width-<?= $id ?>" style="width:3em;"/>
                        : <input type="text" id="imgedit-crop-height-<?= $id ?>" style="width:3em;"/>
                    </span>
                    </p>

                    <p id="imgedit-crop-sel-<?= $id ?>"> 选区：
                    <span class="nowrap"> <input type="text" id="imgedit-sel-width-<?= $id ?>" style="width:4em;"/>
                        &times;
                        <input type="text" id="imgedit-sel-height-<?= $id ?>" style="width:4em;"/>
                    </span>
                    </p>
                </div>
            </div>


            <?php if ($model->hasImage(File::IMAGE_THUMBNAIL)) { ?>
            <div class="panel panel-default imgedit-group imgedit-applyto">
                <div class="panel-heading">
                    缩略图设置 <a href="#" class="dashicons dashicons-editor-help imgedit-help-toggle"></a>
                </div>

                <div class="panel-body">
                    <p class="imgedit-help">您可以编辑图像，并无需影响缩略图。比如，您可能希望有一张只展示图像一部分的方形缩略图。</p>

                    <p>
                        <img src="<?= $model->getImageUrl(File::IMAGE_THUMBNAIL) ?>" width="<?= $thumbW ?>"
                             height="<?= $thumbH ?>" class="imgedit-size-preview" alt="<?= $model->getAlt(); ?>"
                             draggable="false"/>
                        <br/>当前缩略图 </p>

                    <p id="imgedit-save-target-<?= $id ?>">
                        <strong>将更改应用于：</strong><br/>

                        <label class="imgedit-label">
                            <input type="radio" name="imgedit-target-<?= $id ?>" value="all" checked="checked"/>
                            所有图像大小
                        </label>

                        <label class="imgedit-label">
                            <input type="radio" name="imgedit-target-<?= $id ?>" value="thumbnail"/>
                            缩略图
                        </label>

                        <label class="imgedit-label">
                            <input type="radio" name="imgedit-target-<?= $id ?>" value="nothumb"/>
                            除缩略图外所有尺寸
                        </label>
                    </p>
                </div>
            </div>
            <?php } ?>
        </div>
        <div class="imgedit-panel-content">
            <?= $note; ?>
            <div class="imgedit-menu">
                <button class="btn disabled imgedit-crop" title="裁切">
                    <span class="dashicons dashicons-image-crop"></span>
                </button>
                <button class="btn imgedit-rleft" title="逆时针旋转">
                    <span class="dashicons dashicons-image-rotate-left"></span>
                </button>
                <button class="btn imgedit-rright" title="顺时针旋转">
                    <span class="dashicons dashicons-image-rotate-right"></span>
                </button>
                <button class="btn imgedit-flipv" title="垂直翻转">
                    <span class="dashicons dashicons-image-flip-vertical"></span>
                </button>
                <button class="btn imgedit-fliph" title="水平翻转">
                    <span class="dashicons dashicons-image-flip-horizontal"></span>
                </button>
                <button class="btn disabled imgedit-undo" title="撤销" id="image-undo-<?= $id ?>">
                    <span class="dashicons dashicons-undo"></span>
                </button>
                <button class="btn disabled imgedit-redo" title="重做" id="image-redo-<?= $id ?>">
                    <span class="dashicons dashicons-redo"></span>
                </button>
            </div>

            <input type="hidden" id="imgedit-sizer-<?= $id ?>" value="<?= $sizer ?>"/>
            <input type="hidden" id="imgedit-minthumb-<?= $id ?>" value="<?= $minthumb ?>"/>
            <input type="hidden" id="imgedit-history-<?= $id ?>" value=""/>
            <input type="hidden" id="imgedit-undone-<?= $id ?>" value="0"/>
            <input type="hidden" id="imgedit-selection-<?= $id ?>" value=""/>
            <input type="hidden" id="imgedit-x-<?= $id ?>" value="<?= $width ?>"/>
            <input type="hidden" id="imgedit-y-<?= $id ?>" value="<?= $height ?>"/>

            <div id="imgedit-crop-<?= $id ?>" class="imgedit-crop-wrap">
                <img id="image-preview-<?= $id ?>" onload="imageEdit.imgLoaded()" src="<?= Url::to(['file/imgedit-preview', 'id'=>$id, 'rand'=>rand(1, 9999)]); ?>">
            </div>

            <div class="imgedit-submit">
                <input type="button" class="btn btn-default imgedit-close" value="取消"/>
                <input type="button" disabled class="btn btn-primary imgedit-submit-btn" value="保存"/>
            </div>
        </div>
    </div>
    <div class="imgedit-wait" id="imgedit-wait-<?= $id ?>"></div>
    <script type="text/javascript">
        jQuery(function () {
            imageEdit.init(<?= $id ?>);
        });
    </script>
    <div class="hidden" id="imgedit-leaving-<?= $id ?>">未保存的更改将丢失。按“确定”以继续，按“取消”可返回“图片编辑器”。</div>
</div>

backend/views/file/qiNiuUpload.php
<?php

use qiniu\Form;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\File */

$this->title = '上传文件';
$this->params['breadcrumbs'][] = ['label' => '媒体库', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$hint = '允许上传的文件类型：' . $model->getFileExtensionsByField('file') . '。最大大小为：' . $model->getFileMaxSizeByField('file');
?>
<div class="file-upload">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="file-form">
        <?php
        $form = form::begin([
            'putPolicy'=>[
                'scope' => 'css3-test',
                'returnUrl' => url::to(['index'], true),
                'saveKey' => date('y/m/d') . '/' . time() . '$(ext)',
                'extensions' =>  $model->getFileExtensionsByField('file'),
            ],
        ]);
        ?>

        <?= Html::fileInput('file') ?>
        <div class="hint">
        <?= $hint ?>
        </div>

        <div class="form-group">
            <?= Html::submitButton('上传', ['class' => 'btn btn-primary']) ?>
        </div>

        <?php Form::end(); ?>

    </div>
</div>

backend/views/file/update.php
<?php

use common\models\File;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Json;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\File */

$this->title = '更新文件';
$this->params['breadcrumbs'][] = ['label' => '媒体库', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="file-update">
    <h1><?= Html::encode($this->title) ?> </h1>
    <?php $form = ActiveForm::begin() ?>
    <div class="row">
        <div class="col-sm-8">
            <?php if ($model->isImage()){ ?>
                <div class="imgedit-response" id="imgedit-response-<?= $model->id ?>"></div>
                <div id="image-editor-<?= $model->id ?>"></div>
                <div id="image-head-<?= $model->id ?>">
                    <div class="thumbnail">
                    <?= $model->getImage(File::IMAGE_ORIGIN) ?>
                    </div>
                    <p> <?= Html::button('编辑图片', [
                            'id' => 'edit-image-btn',
                            'class' => 'btn btn-sm btn-default',
                            'data-loading-text' => 'Loading...',
                            'autocomplete' => 'off'
                        ]) ?> </p>
                </div>
            <?php } ?>

            <?= $form->field($model, 'name')->textInput() ?>

            <?php
            if ($model->isImage()) {
                echo $form->field($model, 'alt')->textInput();
            }
            ?>

            <?= $form->field($model, 'caption')->textarea(['rows' => 2]) ?>
            <?= $form->field($model, 'description')->textarea(['rows' => 2]) ?>
            <div class="form-group">
                <?= Html::submitButton('更新', ['class' => 'btn btn-primary']) ?>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">文件信息</div>
                <div class="panel-body">
                    <p><span class="fa fa-calendar"></span> 上传于：<?= Yii::$app->formatter->asDatetime($model->created_at) ?> </p>
                    <p> 文件URL：
                        <?= Html::textInput('url', $model->getUrl(), ['readonly' => true, 'class' => 'form-control clone']) ?></p>
                    <p>文件名：<strong><?= $model->file_name ?></strong></p>
                    <p>文件类型：<strong><?= strtoupper($model->getExtension()) ?></strong></p>
                    <p>文件大小：<strong><?= Yii::$app->formatter->asShortSize($model->file_size) ?></strong></p>
                    <?php if ($model->isImage()) { ?>
                        <p>文件尺寸：<strong id="media-dims-<?= $model->id ?>"><?= $model->getWidth() ?>&nbsp;&times;&nbsp;<?= $model->getHeight() ?></strong> </p>
                    <?php } ?>
                </div>
                <div class="panel-footer">
                    <?= Html::a('删除', ['delete', 'id' => $model->id], [
                        'class' => 'btn btn-danger',
                        'data' => [
                            'confirm' => '确定要删除这条数据吗?',
                            'method' => 'post',
                        ],
                    ]) ?>
                </div>
            </div>
        </div>
    </div>
    <?php ActiveForm::end() ?>
</div>
<?php
$options = Json::encode([
   'url' => Url::to(['/file/image-editor', 'id' => $model->id]),
]);
if ($model->isImage()) {
    $js = <<<EOT
    jQuery('#edit-image-btn').click(function() {
        var btn = $(this).button('loading');
        jQuery.ajax({$options})
        .done(function(resp) {
            jQuery('#image-editor-{$model->id}').html(resp).fadeIn('fast');
            jQuery('#image-head-{$model->id}').fadeOut('fast');
        })
        .always(function() {
            btn.button('reset');
        });
    });
EOT;
$this->registerJs($js);
\backend\assets\ImageEditAsset::register($this);
}

backend/views/file/view.php
<?php

use common\models\File;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\File */

$this->title = $model->getName();
$this->params['breadcrumbs'][] = ['label' => '媒体库', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="file-view">

    <h1><?= Html::encode($this->title) ?>
        <?= Html::a('更新', ['update', 'id' => $model->id], ['class' => 'btn btn-sm btn-primary']) ?>
        <?= Html::a('删除', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-sm btn-danger',
            'data' => [
                'confirm' => '确定要删除这条数据吗?',
                'method' => 'post',
            ],
        ]) ?>
    </h1>

    <?php if ($model->isImage()){ ?>
        <div class="thumbnail">
            <?= $model->getImage(File::IMAGE_ORIGIN) ?>
        </div>
    <?php } ?>
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            [
                'attribute' => 'user',
                'value' => $model->user ? $model->user->username : null,
            ],
            [
                'attribute' => 'name',
                'value' => $model->name . '.' . strtoupper($model->getExtension()),
            ],
            [
                'attribute' => 'file_size',
                'format' => 'size',
            ],
            'caption',
            'description',
            'path',
            'url',
            'created_at:datetime',
            'updated_at:datetime',
        ],
    ]) ?>
</div>